### ISSUE TITLE
[Bug] Cannot enter server with 1.2 update

### ISSUE THREAD

**Issue by Toilet-Lord** [WolfieWaffle/Hardcore-Torches-Fabric#1]
When updating from 1.1.1 to 1.2 ( client & server on Fabric) I couldn't join my server anymore.

The only ""Helpful"" thing it tells me is this:

> Toilet_Lord joined the game
> [16:57:30] [Netty Server IO #3/ERROR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "$$0" is null
> [16:57:30] [Netty Server IO #3/INFO]: [STDOUT]: REI: Server failed to synchronize recipe data with the client! Please check the server console log for errors, this breaks REI and vanilla recipe books!
> [16:57:30] [Server thread/INFO]: [Nbt Crafting] Syncing advanced recipe data to player Toilet_Lord
> [16:57:32] [Server thread/INFO]: Toilet_Lord lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "$$0" is null
> [16:57:32] [Server thread/INFO]: Toilet_Lord left the game
> [16:57:32] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2891ms or 57 ticks behind
> [16:57:32] [Server thread/WARN]: handleDisconnection() called twice

Here is the complete log file:
[2022-01-11-7.log](https://github.com/WolfieWaffle/Hardcore-Torches-Fabric/files/7850152/2022-01-11-7.log)

I would love top know what would be causing this and let me know what I can do to help you.
Thank you for checking this out <3

**Comment by WolfieWaffle** [comment]
Sorry for the late response, it seems the recipe data isn't properly transferring to the client or something. I'll see if I can fix it.

**Comment by WolfieWaffle** [comment]
Hm, are you sure the version was the only thing that changed? Looking at the log, I see some recipe errors but not for hardcore torches.

Specifically:

```
[16:50:17] [Worker-Main-6/ERROR]: Parsing error loading recipe crafted:anvil_repair

[16:50:17] [Worker-Main-6/ERROR]: Parsing error loading recipe exlinefurniture:oak_bird_house_recipe

[16:50:17] [Worker-Main-6/ERROR]: Parsing error loading recipe exlinefurniture:spruce_chair_purple_recipe

[16:50:18] [Worker-Main-6/ERROR]: Parsing error loading custom advancement awesomeflooring:recipes/building_blocks/metal_floor: Unknown item tag 'minecraft:iron_ingot'

[16:50:18] [Worker-Main-6/ERROR]: Parsing error loading custom advancement awesomeflooring:recipes/building_blocks/stone_floor: Unknown item tag 'minecraft:cobblestone'
```


You might want to try fixing those first and seeing that is the issue.

**Comment by kittech0** [comment]
same error
[latest.log](https://github.com/WolfieWaffle/Hardcore-Torches-Fabric/files/7980530/latest.log)

**Comment by WolfieWaffle** [comment]
With that file as well, I don't see hardcore torches anywhere in the errors. I see things like:

```[16:21:45] [Worker-Main-3/ERROR]: Parsing error loading recipe survivalplus:pulverizermod/pulverizer_bronze_axe_bronze_ingot
com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'pulverizer_mod:pulverizer'
```

Can you try these steps:

- remove hardcore torches
- log into the server
- put hardcore torches back
- try to log in again

it doesn't seem to me like my mod is the one causing the errors, so could you see if you can log in without it, with nothing else changed?
