### ISSUE TITLE
New Campfire Mechanics?

### ISSUE THREAD

**Issue by cntrik** [WolfieWaffle/Hardcore-Torches-Fabric#2]
_Taken straight from another mod:_
**- New ways to light up a campfire (configurable)**
You have an alternative of using two flints in both hands (main- and offhand) and right-clicking on a campfire which have a chance to light it up! By default, it has a 1/3 probability to be successful, however, you may configure the chance or disable this mechanic altogether. Note: it works only on campfires, you can't ignite blocks with it.
[Campfire Overhaul Link](https://www.curseforge.com/minecraft/mc-mods/campfire-overhaul)

**Comment by WolfieWaffle** [comment]
Well, if another mod already does this I probably don't have a reason to do it myself. It's probably better to make compatibility between the mods, if it is even needed. Just download both.
