### ISSUE TITLE
The LAN server cannot be connected when this mod is installed.

### ISSUE THREAD

**Issue by BrokenDawn627** [WolfieWaffle/Hardcore-Torches-Fabric#3]
You only need to open two client tests to find this problem.

**Comment by WolfieWaffle** [comment]
Could you post the log file here after attempting to log in?

**Comment by WolfieWaffle** [comment]
I have seen that log file but it mentions other mods recipes being missing. It doesn't seem to really give an error related to my mod, so I'm not sure what to do with it.

My only idea, if it is hardcore torches causing the problem, is that it only appears when other mods are installed.

I will have to try running two clients with no other mods installed and see if it works first.

**Comment by WolfieWaffle** [comment]
Well, I tried joining one client with another but it caused a memory issue on my computer, I'm not sure I could do it anyways. I will look at the log though and see if there's anything though.

**Comment by WolfieWaffle** [comment]
I have fixed a possibly different issue with joining servers in the 1.19 version of the mod, see if that version works

**Comment by WolfieWaffle** [comment]
closing now as there was no response, tell me if you do end up testing it with the latest version
