### ISSUE TITLE
torces are crafted as everlasting

### ISSUE THREAD

**Issue by lordi-erez** [WolfieWaffle/Hardcore-Torches-Fabric#4]
![image](https://user-images.githubusercontent.com/44799224/153702216-2ae4adb1-fd61-4db1-afb2-e0a4ca444ab2.png)

**Comment by WolfieWaffle** [comment]
Are you using the latest version?

**Comment by WolfieWaffle** [comment]
I believe this was a result of datapacks loading incorrectly, and only happened on forge. if you are still having this issue on FABRIC on the latest version please comment.
