### ISSUE TITLE
Can't get in server when v1.2 (and +) is loaded

### ISSUE THREAD

**Issue by Toilet-Lord** [WolfieWaffle/Hardcore-Torches-Fabric#5]
Title explains the problem well but there's something more to it. Idk what it does but even if you remove the mod, you can't load in the server again **until the whole dedicated server is remade**/ the file affected is renewed or something like that

This might be an incompatibility with another mod or smt but I spent 2 days trying to find what mod was causing this.
.
.
.
**||The v1.1.1 of the mod works just fine, only 1.2 and after doesn't||**

How to recreate:
1. Run 1.1.1 (runs fine)
2. Update mod to v1.2 or 1.3.3 on both client and dedicated server
3. Start server & client
4. Connect to server
5. Fucking die (not really just send the last few lines in log)

**Here's the server log:**
[latest.log](https://github.com/WolfieWaffle/Hardcore-Torches-Fabric/files/8112909/latest.log)

Thank you for checking out this issue and let me know if I can do anything else <3

**Comment by WolfieWaffle** [comment]
unfortunately I don't see my mod mentioned anywhere in that log so I'm not sure where to even look in my code for an issue. have you tried to see if this bug exists with hardcore torches being the only mod installed?

**Comment by WolfieWaffle** [comment]
I have just fixed a server joining issue in 1.19 version, see if that works

**Comment by WolfieWaffle** [comment]
closing this now due to inactivity. if you test this on the 1.19.3 version and it's still bugged, add a comment.
