### ISSUE TITLE
No config for shift-click lantern pickup (plus a crafting thing)

### ISSUE THREAD

**Issue by SPYROHAWK** [WolfieWaffle/Hardcore-Torches-Fabric#9]
One thing I found really amazing about this mod is how modular it is, almost everything is controlled by the config file. So I was really surprised to see that the functionality to pick up a lantern by shift-clicking cannot be disabled.

I'm using the 1.18.2 Fabric version of the mod. I want to use the mod as part of an adventure map, but when players are in adventure mode, they can pick up the lanterns via shift-click but can't place them down again. It would be great to be able to disable this so they don't accidentally hurt their own progression by getting rid of all the lights.

---

There is an alternate thing as well.

The players picking up the lanterns, by itself, isn't really the issue. I have them confined so they burn even while in the player's inventory, and I have dynamic lights so they emit light while being held (although another config would be nice to make them only burn out while held, and not in the general inventory would be nice). The issue comes with refueling. Since they can't place the lanterns down, there's no way to refuel them.

It would be really nice if an option was added to craft an empty lantern together with the oil lamp thing to refuel the lantern (and maybe light it) so it can be managed entirely within the inventory.

---

But that's more of an alternate solution just for my specific scenario. The shift-click pickup config is the main thing I think is an oversight.

**Comment by WolfieWaffle** [comment]
that should be easy enough to add

**Comment by WolfieWaffle** [comment]
oh yea I added this to the latest forge version

...but I just realized this is for fabric

**Comment by WolfieWaffle** [comment]
hopefully not too late to be useful, but im gonna add this today to the fabric version
